### ISSUE TITLE
Discontinuous atom numbering splits residues

### ISSUE THREAD

**Issue by slochower** [Amber-MD/cpptraj#1012]
I'm trying to use a PDB file as topology that has an entry like this:

```
[...]
ATOM    962  N   LEU A1552       4.150  -4.035  -7.810  0.00  0.00      C2   N
ATOM    963  CA  LEU A1552       3.782  -5.191  -7.047  0.00  0.00      C2   C
ATOM    964  C   LEU A1552       4.574  -5.211  -5.764  0.00  0.00      C2   C
ATOM    965  O   LEU A1552       4.044  -5.493  -4.662  0.00  0.00      C2   O
ATOM    966  H   LEU A1552       4.703  -4.095  -8.653  0.00  0.00      C2   H
ATOM    967  HA  LEU A1552       2.742  -5.094  -6.734  0.00  0.00      C2   H
[...]
ATOM   2246  CB  LEU A1552       3.964  -6.378  -8.016  0.00  0.00      C2   C
ATOM   2247  CG  LEU A1552       3.188  -7.607  -7.461  0.00  0.00      C2   C
ATOM   2248  CD1 LEU A1552       1.634  -7.430  -7.205  0.00  0.00      C2   C
ATOM   2249  CD2 LEU A1552       3.495  -8.664  -8.446  0.00  0.00      C2   C
ATOM   2250  HB2 LEU A1552       3.589  -6.109  -9.003  0.00  0.00      C2   H
ATOM   2251  HB3 LEU A1552       5.038  -6.555  -8.076  0.00  0.00      C2   H
ATOM   2252  HG  LEU A1552       3.582  -7.849  -6.474  0.00  0.00      C2   H
```

Note the discontinuous atom ordering for the same residue number. (This is an artifact of trying to use `cpptraj` to process Demond trajectories and using VMD to convert the CMS to PDB. Well, it probably traces back to how the CMS was setup, but I don't have control over the conversion to PDB and Schrodinger's own tools will produce a similar PDB output. VMD does not write `CONECT` records in the PDB.)

When running through `cpptraj` (i.e., doing some processing and writing out a `prmtop`/`nc`), this LEU residue becomes two residues. Ideally, that wouldn't happen. I can't just reorder the atoms in the PDB to make the numbering contiguous, because then the original trajectory won't match. Is there a way to tell `cpptraj` to use residue templates to determine bonding within a residue number? (Related question: is there a way to preserve the original residue numbering from the PDB after running commands like `strip`?)

**Comment by drroe** [comment]
I'll look at this today. If you get a chance, could you please attach the PDB in question? Thanks.

**Comment by drroe** [comment]
> Note the discontinuous atom ordering for the same residue number.

OK, I think I read this wrong initially. It's not just that the atom serial numbers are not contiguous - the residue itself is split and scattered throughout the PDB? I think this not valid for the PDB format:

" The sequence implied by ATOM records must be identical to that given in SEQRES, with the exception that residues that have no coordinates, e.g., due to disorder, must appear in SEQRES." (from https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM).

I know you said you got the PDB from Desmond->Cpptraj->VMD, but I would like to know more details - if Cpptraj is somehow splitting residues in this way that's not great.

I don't see an easy solution for this. One of the assumptions I made in Cpptraj is that atoms in a given residue are contiguous. It's possible to deal with non-contiguous residues (Cpptraj can handle non-contiguous molecules just fine), but it would require a significant amount of work. Changing the code to handle non-contiguous molecules was a fair amount of work (see #845). Is the residue split from the very beginning in Desmond?

**Comment by slochower** [comment]
> I know you said you got the PDB from Desmond->Cpptraj->VMD, but I would like to know more details - if Cpptraj is somehow splitting residues in this way that's not great.

I mutated the residue in the Maestro GUI using the built-in Builder tools. Because this residue was mutated, it appears that Maestro kept the backbone atoms in-place and added the side chain somewhere else in the database/file. I saved a CMS and simulated with Desmond. Everything looks good: the residue is attached and behaves as expected. I assume the issue comes when either VMD or Schrodinger tries to parse the CMS into a PDB (both end up splitting the residue as above) and I'm guessing this is because the atoms are located non-contiguously in the CMS connection table (I don't really know how the CMS format works, so this is a guess). 

So the answer to your question is: no, the residue is not split by Desmond but the residue becomes split when writing the PDB. 

#845 looks like a bear, I agree. Perhaps there is another creative solution. I know that `cpptraj` can do grid searching for bonds. Would an approach like that work here?

**Comment by drroe** [comment]
>  I know that cpptraj can do grid searching for bonds. Would an approach like that work here?

The issue here isn't necessarily finding the bonds. It's the underlying assumption made in cpptraj that in a given topology all atoms in a given residue are contiguous (i.e. a residue has a "start" atom and a "stop" atom, between which all atoms are in that residue). To handle non-contiguous residues you cant just do:
```C++
for (int atom = start_atom; atom != stop_atom; atom++)
  <something>
```
And have `<something>` apply to the entire residue, you have to introduce the concept of a residue having multiple segments, then rewrite each piece of code that does things in the way above to be "segment-aware" (this is essentially what #845 was for molecules).

I _think_ the simplest approach here might be to introduce a new action called something like `mergeres` that will allow users to manually merge 2 (or maybe more) residues into a single residue. It would be spiritually similar to the `fixatomorder` command, which was designed to fix non-contiguous molecules. Alternatively I could try to update `fixatomorder` to recognize 
"split" residues as well. Maybe both? I'll have to think about this. It will certainly require some work and testing. If you could post the problematic PDB or send it to my email directly it would be a helpful test case.

**Comment by drroe** [comment]
Hi, thanks for sending me the file. So I completely spaced on this, but there is a `pdborder` option for the `fixatomorder` action that I _completely_ forgot about, the purpose of which is to organize atoms by PDB information. I ran your `disrupted-residues.pdb` PDB through it via:
```
parm disrupted-residues.pdb
trajin disrupted-residues.pdb
fixatomorder pdborder
trajout fixed.pdb
```
and `fixed.pdb` seems like it might be OK in terms of residues. There are however 2 other issues that may or not be a problem for you. The first is that the `NMA` residue (some kind of terminal methyl group I guess?) has the same residue number (1627) and chain ID (A) as another residue, ALA 1627. I don't think this is permissible in the PDB standard but doesn't bother cpptraj, it will still place them in separate residues. The second is that the `disrupted-residues.pdb` has extra information in columns 73-74 (`C2`), which again while not part of the PDB standard it won't mess up cpptraj reading it. However, if that info is important for another program note it will be lost in `fixed.pdb`. It's not hard to add back but I wanted to make you aware of it.

Sorry for spacing on this option before. I've added so much stuff over the years sometimes I lose track. Try it out and let me know if it works for you or if it needs tweaking.

**Comment by slochower** [comment]
Ah, this is interesting. This *does* appear to work, at least at first. I'm not entirely clear on how to use this in conjunction with trajectories though, without scrambling things. Let me make this a little more complicated. Let's say I have an initial script that looks like

```
parm disrupted-residues.pdb
trajin disrupted-residues.dcd
fixatomorder pdborder
autoimage
parmwrite out fixed.prmtop
trajout fixed.nc
run
quit
```

Now, the trajectory `fixed.nc` is scrambled. Is this because fixing the atom order in the topology doesn't also fix the atom order in the trajectory? I don't think I can pre-fix the ordering with the snippet you posted because then things will be scrambled when I read in the trajectory. I think I need something that fixes the atom order for both at the same time, right? Or am I missing something simple?

Re: other junk. Yes, this is added by Maestro and gets put into the PDB during the conversion (which I have to do using VMD, because Schrodinger's own structure converter will omit the pseudo atoms that lead to mismatches in the number of atoms in the topology and trajectory).

**Comment by drroe** [comment]
Hi, not sure if this is your issue but you want to write the topology out in the `fixatomorder` command, e.g.:
```
fixatomorder pdborder parmout fixed.prmtop
```
The reason is that the topology is not permanently modified by `fixatomorder` (if it was, it would no longer correspond to the original `disrupted-residues.dcd` trajectory). So to sum up, try:
```
parm disrupted-residues.pdb
trajin disrupted-residues.dcd
fixatomorder pdborder parmout fixed.prmtop
autoimage
trajout fixed.nc
run
```
Then `fixed.prmtop` should correspond to `fixed.nc`.

**Comment by drroe** [comment]
@slochower Is this issue still a problem?

**Comment by slochower** [comment]
Oh, no. I'm sorry I forgot to close this. (Yes, the problem still happens when exporting Desmond trajectories that have discontinuous numbering (e.g., from mutating a residue in Maestro) but the above fix is workable.)
