### ISSUE TITLE
Density out file from NPT 

### ISSUE THREAD

**Issue by Saqlain5565** [Amber-MD/cpptraj#1026]
Hi all i want to get the density out file from NPT using AMBER.
i have .nc file i am running cpptraj but could not able to get density out file .
parm wtr_1.prmtop
trajin eq_npt.nc
density :WAT out wato.agr xydy
i use these codes but no file generated.
 DENSITY: Determining number density for 1 masks.
	routine version: 1.0.3
	Delta is 0.010000
	Axis is Z
	Data set name is 'DENSITY_00003'
	Data set aspect [avg] holds the mean, aspect [sd] holds standard deviation.
	Bin coordinates will be to bin center.
	Output to 'wato.agr'
this comes but no file presented.
kindly help me out in this.

**Comment by drroe** [comment]
Hi,
Is this being run using a script (e.g. `cpptraj -i cpptraj.in`) or interactively? If you're running interactively, have you typed `run` to actually start the run?

**Comment by Saqlain5565** [comment]
yeah i got it, i did not typed run to actually start cpptraj. thanks for the timely response.
but the file i got wato.agr is seems so arbitary or do it be shown correctly on only GRACE i use origion for .agr file . but the sysmet shows AVERAGES   OVER  200000 STEPS & R M S fluctuations is very consistent.
so i want to confirm is system calculated average density is relaible ?

**Comment by drroe** [comment]
>  but the sysmet shows AVERAGES OVER 200000 STEPS & R M S fluctuations is very consistent.

Based on the input you gave, you're calculating the number density along the xy plane for water - this is not going to be the same as the overall system density that gets reported in the MDOUT file (which is what you would get from cpptraj `density` if you didn't specify a mask). From the onboard help for `density`:
```
If one or more masks are specified, calculate specified density of selected
  atoms along a coordinate. Otherwise calculate the total system density.
```
It sounds like maybe what you want is the overall density of the water? You could always get that by calculating the total mass of the water in amu with the `mass` command then dividing by the volume (in Ang^3) calculated with the `volume` command, e.g.
```
parm myparm.parm7
trajin mytraj.nc
# Calculate mass of water, store in variable MASS
mass :WAT name MASS
printdata MASS
# Calculate volume at each frame, store in variable VOL
volume VOL
run
# Calculate density from mass over volume, store in variable DENSITY
DENSITY = MASS / VOL
writedata density.dat DENSITY
```
Keep in mind that if there is any solute in your system, the density you get will look low because you're not considering the solute. Hope this helps.

**Comment by Saqlain5565** [comment]
yeah its really helpful i got the density.dat file , but as you have said the density shows less values than my system generated values during NPT eq.out .
 I am using pure water system no solute involved so my point of concern is i must get the same density out file as it shows in eq.out in NPT.

**Comment by drroe** [comment]
> but as you have said the density shows less values than my system generated values during NPT eq.out .

Since CPPTRAJ is calculating density from the trajectory frames, there are 2 things to consider: 
1) What is the write frequency of the trajectory and output files (i.e. `ntwx` and `ntpr` namelist vars in Amber). If these are different, you're getting values at different times, so they won't necessarily match up. 
2) By default, the coordinates from trajectory frames are one step ahead of the energy and density values printed in MDOUT (this is well known and is the result of the leapfrog integration). So unless you're writing every time step, the values you get will not match.

All this said, the averages should be quite close.

**Comment by Saqlain5565** [comment]
Hello my last issue was resolved and i learn a lot from your answers.
Now,
i want to create tip5p.pdb file for Amber but i could not able to create it.kindly share a process of it if you have already.
kind regards.

**Comment by drroe** [comment]
> i want to create tip5p.pdb file for Amber but i could not able to create it.kindly share a process of it if you have already.
kind regards.

You'll probably get a better response for a general question like this on the [Amber Mailing List](http://lists.ambermd.org/mailman/listinfo/amber)
