### ISSUE TITLE
wrong number of mols

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#104]
So I am playing with parmed to convert `gro` file to `psf` so cpptraj can read.

```python
In [49]: pmd.load_file('frame0.gro').save('test.psf', overwrite=True)

In [50]: pt.load_topology('test.psf')
Out[50]: <Topology: 22 atoms, 3 residues, 22 mols, non-PBC>
```

The problem is ``cpptraj`` detects 22 mols (= 22 atoms) for 3 residues. Should cpptraj has better detection?

cpptraj log
```
PARAMETER FILES:
 0: 'test.psf', 22 atoms, 3 res, box: None, 22 mol
```

**Comment by swails** [comment]
That's the wrong conversion to do here.  GRO files don't have any bond information, so no bonds get written to the PSF file.  Since the PSF file *has* bonds, cpptraj doesn't do any "guessing" based on distances like it does for PDB files.

With no bonds, every atom is its own "molecule", which is the right result.  In reality, GRO files are bastardized PDB files.  Converting to a PDB will trigger cpptraj to create bonds *and* it will preserve the coordinates present in the original GRO file (both of which are lost when converting to PSF).

At some point I will add automatic bond determination to ParmEd PDB (and CIF/GRO) reading, but until that happens this is a limitation you have to keep in mind.

**Comment by swails** [comment]
> That's the wrong conversion to do here. GRO files don't have any bond information, so no bonds get written to the PSF file. Since the PSF file has bonds, cpptraj doesn't do any "guessing" based on distances like it does for PDB files.

Also, PSF files don't have coordinates, so cpptraj couldn't guess even if it wanted to :)

**Comment by drroe** [comment]
So in reality, cpptraj came up with the correct number of molecules for this topology :-)

**Comment by hainm** [comment]
> At some point I will add automatic bond determination to ParmEd PDB (and CIF/GRO) reading, but until that happens this is a limitation you have to keep in mind.

thanks.
