### ISSUE TITLE
seperate "ifdefs " for BLAS, LAPACK and ARPACK

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#108]
just summary what we've been discussing on gchat.

Currently there is no way to turn on LARPACK, BLAS separately. If using --with-blas, --with-lapack, cpptraj still require libarpack. My idea is to link cpptraj to numpy library (does not have libarpck). This will make it easier to ship libcpptraj via conda.

**Comment by swails** [comment]
What is arpack *not* needed for the lapack and blas *are*?  (And what is arpack needed for?  Just matrix routines?)

**Comment by swails** [comment]
The more flexibility we add on stuff like this (right now we either have *all* math libs or *none*), test coverage becomes exponentially harder.

**Comment by hainm** [comment]
this is from Dan: "arpack is required when not calculating all eigenvectors, e.g. when # vecs < # potential vecs"

**Comment by hainm** [comment]
for the 'arpack' problem, I don't have conda build for it and don't want user install arpack by themself. It's not problem with Amber user, but just thinking about non-Amber user, who don't mind installing AmberTools.

**Comment by hainm** [comment]
It's great if we have conda build for `ARPACK`. Already google and found none. Seem nobody's interested in?

**Comment by rmcgibbo** [comment]
I think I can conda-build arpack

**Comment by hainm** [comment]
> I think I can conda-build arpack

:+1:

**Comment by rmcgibbo** [comment]
OTOH, in general, unless you have very sparse or structured matrices and specialized matrix-vector operations for them, or matrices so large that they don't fit in memory, my experience is that Arnoldi is not competitive with direct methods, even if you only want 1 eigenvector.

**Comment by swails** [comment]
> OTOH, in general, unless you have very sparse or structured matrices and specialized matrix-vector operations for them, or matrices so large that they don't fit in memory, my experience is that Arnoldi is not competitive with direct methods, even if you only want 1 eigenvector.

This has also been my experience.  Admittedly it was not an exhaustive test (and it was a long time ago), but diagonalizing an MM Hessian (when we were trying it out for MMPBSA.py) took basically the same time for Arnoldi with 1 vector as it did for the full diagonalization using one of the direct subroutines.  Once we got up to a small handful of vectors (maybe 4 or 5?) it was actually quite a bit slower, so we ditched it completely.

**Comment by hainm** [comment]
@drroe 

so do we really need ARPACK? :D

**Comment by drroe** [comment]
> so do we really need ARPACK? :D

It's not clear that it is needed - I only included it in cpptraj because that is how ptraj handled the case of number requested eigenvecs < matrix order, and (almost) completely preserving backwards compatibility with ptraj output was one of the early selling points of cpptraj.

As I mentioned in our earlier conversation @hainm, I think it would not be too difficult to separate out ARPACK from BLAS/LAPACK and just use methods from the latter when the former is not available. My feeling is that most users won't notice the difference. This way the ARPACK code is still there if it is ever required for some reason, but compiling becomes a bit easier in some cases.

**Comment by drroe** [comment]
> so do we really need ARPACK? :D

I'm in the middle of testing some code that does not use ARPACK, just regular LAPACK. Turns out there can be some pretty significant speed differences when the matrix becomes large enough. For 66 eigenvectors for example, there's almost no difference. However, for a larger system (1241 atoms, 3723 eigenvectors) the speed is orders of magnitude different (~1 s with ARPACK, ~349 s without). So it's definitely worth it to keep the ARPACK stuff in there, but I also like having the option to build without it and still include BLAS/LAPACK.

**Comment by hainm** [comment]
> ~1 s with ARPACK, ~349 s without
wow, it's worth using arpack.

**Comment by drroe** [comment]
Fixed via #132

**Comment by hainm** [comment]
per arpack stuff, I decide to build conda binary file for pytraj with only libcpptraj/netcdf/lacpack only. Too many dependences introduce many headaches. (I just had issues with dynamic linking stuff, so don't want to spend time on this).

If users want more (arpack, fftw3, ..), just tell them to install the source code by them-self. 

It's convenient that when pytraj is shipped with AmberTools, all the dependencies are ready included.
