### ISSUE TITLE
Multidihedral pca -> sidechain pca?

### ISSUE THREAD

**Issue by H-EKE** [Amber-MD/cpptraj#1108]
Hi @drroe ,

1)
I was looking this tutorial about dihedral pca ()

```
multidihedral MyTorsions phi psi resrange 6-9 out PhiPsi_6-9.dat
```
I was wondering if one could use that for sidechains, without needing to specify each chi1-chi2 for every residue, as shown here:

```
multidihedral dihtype chi1:N:CA:CB:CG out custom.dat
```
2)
A last unrelated question, I was trying to follow this tutorial (https://ambermd.org/tutorials/advanced/tutorial41/index.php) where they do PCA too. I had a doubt regarding this part

**Figure 2. PCA projection of 50 ns simulation.
Using a text editor, frames of the simulation representing each cluster were identified and turned into PDB
files using VMD.** 

Would you know how the did this? Or if htere is an automated way to do this thourg python?

Thanks in advance!

**Comment by drroe** [comment]
So sorry I missed this the first time around! Since you closed it hopefully your questions were answered, but just in case they weren't, yes you should be able to create custom dihedral types the way you proposed - hopefully that worked for you.

Second, if you want to print out trajectory files from clustering you would use the `clusterout <trajfileprefix> [clusterfmt <trajformat>]` keywords of the `cluster` command, e.g. `clusterout MyCluster.pdb clusterfmt pdb` which should create `MyCluster.pdb.cX` where X is the cluster number.

**Comment by H-EKE** [comment]
Hi @drroe,

No problem at all, and thank you for taking the time to respond!

I managed to get it working, but unfortunately, it didn’t match my hypothesis.

I will try clusteout, so far I just used to scikit-learn and it worked fine.
