### ISSUE TITLE
add SetGBradii to Topology

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#133]
currently, we can only choose different existing GB radii set based on `string`

`void SetGBradiiSet(std::string const& s) { radius_set_ = s;              }`

What do you think about adding
`void SetGBradiiSet(vector<double> s)`?

it's good for this too https://github.com/Amber-MD/cpptraj/issues/102 and it's more flexibile.

**Comment by drroe** [comment]
The `SetGBradiiSet()` function is just used to record the corresponding string from the Amber topology file, i.e. it is for bookkeeping purposes only. Setting this does not change the GB radii.

@hainm What did you think about the reading radii in from PQR files that I mentioned at the end of #102? Otherwise you can use `Topology::SetAtom(int).SetGBradius(double)`.

**Comment by hainm** [comment]
> Setting this does not change the GB radii.

yeah, I am aware of this, just suggest if we can extend this function (or make another function).

> What did you think about the reading radii in from PQR files that I mentioned at the end of #102

I would like to have pytraj and cpptraj talk 'internally' rather making unnecessary file. 

> Otherwise you can use Topology::SetAtom(int).SetGBradius(double).

this sounds good for me. I will try it and close this issue when done.

**Comment by hainm** [comment]
close, done with pytraj https://github.com/Amber-MD/pytraj/pull/974
