### ISSUE TITLE
circular dna and nastruct, reading from pdb and prmtop (with crd) give different result

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#166]
Just playing around and I am too lazy to type prmtop with prmcrd, so I just pick pdb file (`pt.iterload(pdb))`

The files are from here:
$AMBERHOME/test/circ_dna/

- circ.pdb

- prmtop
- prmcrd

Two situations

```bash
parm circ.pdb
trajin circ.pdb
nastruct groovecalc 3dna naout dat
```

This does not result majour and minor groove output

Got warning too:
`Warning: PDB line length is short (55 chars, expected 80).`

```
parm prmtop
trajin prmcrd
nastruct groovecalc 3dna naout dat
```

This one does. It's understandable since prmtop and prmcrd were built by tleap from circ.pdb

But can we enhance cpptraj here? Given that tleap can read pdb well. I've tried 3DNA and got output for major and minor groove with that pdb file.

**Comment by hainm** [comment]
output from 3DNA: https://github.com/Amber-MD/pytraj/blob/master/tests/data/Test_NAstruct/x3dna_circ/circ.out

**Comment by hainm** [comment]
seem legit with ParmEd:

```python
In [3]: pmd.load_file('circ.pdb')
Out[3]: <Structure 4528 atoms; 200 residues; 0 bonds; NOT parametrized>
```

**Comment by drroe** [comment]
I don't think there is a real issue here. The problem is that the structure is a bit strange, so the bond detection in cpptraj doesn't link up some of the fragments:
```
	Topology circ.pdb contains 4528 atoms.
		Original filename: /home/droe/Amber/GIT/amber/test/circ_dna/circ.pdb
		200 residues.
		117 molecules.
		4911 bonds (428 to H, 4483 other).
		Box: None
```
VMD (which also does bond search by distance) has a similar issue:
```
Info) Analyzing structure ...
Info)    Atoms: 4528
Info)    Bonds: 4890
Info)    Angles: 0  Dihedrals: 0  Impropers: 0  Cross-terms: 0
Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
Info)    Residues: 200
Info)    Waters: 0
Info)    Segments: 1
Info)    Fragments: 138   Protein: 0   Nucleic: 22
```
Since the fragments are not properly connected there are effectively no base pair steps, and this is what causes the output to differ from 3DNA. 3DNA does not search for bonds by distance - it assumes the residues are connected in a certain way and I believe uses only base pair reference axis distance to determine steps.

There are two solutions. One is to load the PDB using `parm <file> bondsearch 0.9` to increase the bond search distance cutoff. This correctly identifies the two molecules (although it seems to find too many bonds) and the results from `nastruct` then seem to match 3DNA.

The other, better solution is to use the topology file which actually has correct bond information and the restart instead. If you do this you get `nastruct` output that matches 3DNA (actually it's a bit better since it gets the groove widths for *all* base pair steps). The PDB format may be convenient but it is a poor one from an analysis standpoint.

> Got warning too:
> Warning: PDB line length is short (55 chars, expected 80).

This is perfectly legitimate. The PDB standard (http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM) specifies that `ATOM` records are 80 characters long. Anything short of that does *not* conform to the PDB standard. Since the `ATOM` records of the PDB file in question stop after the `Z` coordinate column, cpptraj helpfully warns that the line is short (so you know you are missing some information, in this case occupancy, temperature factor, element, and charge).

**Comment by hainm** [comment]
thanks Dan.
