### ISSUE TITLE
speeding pairwise rmsd, clustering + more efficient to iterate Trajectory

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#185]
currently `cpptraj` has in memory Dataset CRD for fast iterating (good for computing rms2d, ...) and for less memory consuming (using float32).

However creating and iterating this Dataset is not efficient since cpptraj does the copy twice (convert input frame from double to float for reading frame, then converting float to double when outputting frame).

I have benchmark for rms2d for lysozyme, 2000 frames.

- strip atoms before dump to CRD set

```python
parm lysozyme.top
trajin lysozyme.nc 1 2000
strip !@CA
rms2d @CA out test0.dat
```
This input took **2** seconds to finish the analysis (log: `TIME: Analyses took 2.0946 seconds.`)

vs 
- not strip atoms

```python
parm lysozyme.top
trajin lysozyme.nc 1 2000
rms2d @CA out test1.dat
```

Two times slower `TIME: Analyses took 3.9063 seconds.` (the output from 1st and 2nd are matched)

So my suggestion is to consider sacrificing memory for speed for some actions: for example, if we only need to calculate pairwise rmsd for backbone atoms, we only need to create CRD dataset for those atoms (no water, no ions, ...), so memory is not a big deal.

**updated**: The `two times` slower might due to on the fly stripping atoms?

**Comment by hainm** [comment]
Let me compare cpptraj speed in iterating CRD set with pytraj's Trajectory

I made two CRD datasets (d0: stripped atoms, d1: all atoms).

```python
Out[21]:
pytraj.Trajectory, 1000 frames:
Size: 0.043832 (GB)
<Topology: 1961 atoms, 129 residues, 1 mols, non-PBC>


In [22]: d0
Out[22]:
pytraj.DatasetCoordsCRD, 1000 frames:
Size: 0.043832 (GB)
<Topology: 1961 atoms, 129 residues, 1 mols, non-PBC>


In [23]: d1
Out[23]:
pytraj.DatasetCoordsCRD, 1000 frames:
Size: 0.002883 (GB)
<Topology: 129 atoms, 129 residues, 129 mols, non-PBC>
```

This is iterating time for pairwise rmsd (no really calculation was done), just something like

```python
for _ in traj:
   for _ in traj:
         pass
```

```python
In [24]: %time traj_()
CPU times: user 328 ms, sys: 0 ns, total: 328 ms
Wall time: 328 ms

In [25]: %time d0_()
CPU times: user 21.4 s, sys: 0 ns, total: 21.4 s
Wall time: 22 s

In [26]: %time d1_()
CPU times: user 1.22 s, sys: 0 ns, total: 1.22 s
Wall time: 1.22 s
```
|                                     |                             |
|-----------------------------  |----------------------|
| pytraj's traj                  |  0.328 seconds |
| CRD set d0 (all atoms)             |  22.00 seconds |
| CRD set d1 (stripped atoms)   |  1.22 seconds |

**Comment by hainm** [comment]
Disclaimer: I might misunderstand how cpptraj works. :D

**Comment by drroe** [comment]
I'm not really clear on what the issue is here. It is of course faster to iterate over a smaller coordinates data set. Users are already free to do this if they wish. It's not done automatically because you may want the other coordinates for something else. Take clustering for example: you may only cluster on a subset of atoms (like CA) but when you output structures (like average or representative) you'd like all of the original atoms present. If you automatically stripped everything but CA before clustering then you could only output structures containing CA atoms. Cpptraj has the flexibility to get the best of both worlds of course; you can cluster on the stripped CA trajectory and then use the cluster number vs time data set to do your coordinate processing in a subsequent step for example.

Let me know if I'm not understanding your original concern.

**Comment by hainm** [comment]
> . It's not done automatically because you may want the other coordinates for something else.

make sense to me now. thanks.
