### ISSUE TITLE
Invalid command or expression.

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#207]
(separated from #206)

```python
In [5]: Command.dispatch(state, 'parm data/tz2.ortho.parm7')
Error: Data set with name 'parm' not found.
'parm data/tz2.ortho.parm7': Invalid command or expression.
```

I've been trying to read cpptraj code but get lost. Give hint please.

**Comment by hainm** [comment]
phew, pytraj is now compilable and runnable. Still wait for your feedback about Command::Dispatch so we can merge. :+1:

**Comment by drroe** [comment]
> I've been trying to read cpptraj code but get lost. Give hint please.

Previously all commands were stored in a static array inside the Command class that contained function pointers; there was no need for allocation of the array. Now, the Command class is still static, but because static function pointers are no longer used, the array inside Command needs to be allocated. So if you're not calling Command::Init(), the array of commands is empty. You also need to call Command::Free() before the program exits to free the memory used by the commands. Does this make sense now?

**Comment by hainm** [comment]
> Now, the Command class is still static, but because static function pointers are no longer used, the array inside Command needs to be allocated. 

ok. I see. I will add Init and Free.

**Comment by drroe** [comment]
Just let me know when everything is good to merge. Thanks!

On Sunday, December 13, 2015, Hai Nguyen <notifications@github.com> wrote:

> Now, the Command class is still static, but because static function
> pointers are no longer used, the array inside Command needs to be
> allocated.
>
> ok. I see. I will add Init and Free.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/cpptraj/issues/207#issuecomment-164279949>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
The command works now. good to merge.

**Comment by drroe** [comment]
All merged.

**Comment by hainm** [comment]
can you push to amber repo to (if have a chance).

**Comment by drroe** [comment]
Done. Let me know if you see any problems.
