### ISSUE TITLE
turn off email?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#21]
Dan,

Can I turn off email notification so traivs does not send email to everyone?

```python
notifications:
  email: false
```

In here: https://github.com/Amber-MD/cpptraj/blob/master/.travis.yml

**Comment by hainm** [comment]
or you can change to your email (in case you prefer to get notification from email) when there is successful PR.

http://docs.travis-ci.com/user/notifications/

**Comment by swails** [comment]
I like to see when the build has broken.  Travis never sends me emails unless a merge or push has broken.

What is this supposed to turn off?

**Comment by drroe** [comment]
@hainm I'm not 100% sure what you mean - I actually don't know if I've ever received any emails from Travis. 
@swails and @hainm is there a recommended setup besides the default?

**Comment by swails** [comment]
Here is what the Travis documentation states:

```
By default, email notifications will be sent to the committer and the commit author, if they are members of the repository (that is, they have push or admin permissions for public repositories, or if they have pull, push or admin permissions for private repositories).

And it will by default send emails when, on the given branch:

a build was just broken or still is broken
a previously broken build was just fixed
```

I personally like this behavior and keep the defaults for ParmEd.  @hainm turns them off for pytraj.  If Dan is the only person that merges PRs for cpptraj [1], then this shouldn't send out emails to people besides him, right?

Note that Travis doesn't send emails on failed PRs by default (to my knowledge, since it's not part of the `Amber-MD/cpptraj` repo until merged), only if a merged PR then fails Travis (and this is something I would *want* to know about).

[1] I think this is a good policy for cpptraj right now for anything modifying any code.  It ensures Dan will know all of the code going into it and will help with code quality management.  The contributor list is small enough that Dan shouldn't get overwhelmed with PRs and issues (unlike, for instance, the `numpy` project which has multiple committors), and other projects I contribute to adhere to this.  And this can always be revisited in the future if Dan leaves the field for whatever reason or the number of PRs skyrockets.

**Comment by hainm** [comment]
oh, I got email from travis saying the cpptraj build passed when I PRed. I thought travis would send email to all people (turns out only sent to me).

**Comment by swails** [comment]
That's because you accidentally pushed directly to the amber-md/cpptraj repo rather than your personal fork.

**Comment by hainm** [comment]
No, The email title is this "Passed: hainm/cpptraj#1 (master - f39c178)"

**Comment by swails** [comment]
I've never gotten an email from Travis about one of my PRs passing.  And all of the repos I have ever contributed to use the default email settings...
