### ISSUE TITLE
reorganize cpptraj folder

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#24]
I got lost when starting to look at cpptraj's code in the begining. Mostly because there are so many files in a single folder. I think it's good idea to reorganize it. Just give example of  [plumed](https://github.com/plumed/plumed2/tree/master/src), which has similar coding style as cpptraj. 

Another advantage is much easier to browse code with phone. (it took very long thumb swiping for me to read `Trajout_Single.cpp` file (near the end).

PS: to avoid issues out of your (Dan) radar, you can create different labels for different topics, just like in [pandas's repo] (https://github.com/pydata/pandas/issues). In my opinion (and Jason too?), issues in github are much more convenient than g-doc.

**Comment by swails** [comment]
@hainm -- you can always assign labels.

> Another advantage is much easier to browse code with phone.

But when do you code on your phone? ;)

**Comment by hainm** [comment]
I need to understand the code first :p

**Comment by drroe** [comment]
@hainm I'm very resistant to this idea right now. The main problem I have when code is in different folders (an example that comes to mind is Gromacs) is that it then becomes more difficult for me to find out where specific functions are (since I don't have a fancy IDE). For example, if I want to find out where I've used `integerToString()` all I have to do now is `grep -l "integerToString(" *.cpp`. To me that's a cost that is not paid for by having things look a little nicer. In my opinion keeping the file names consistent (e.g. Action_X) is fine for the time being. Maybe as time goes on I'll warm up to this idea but right now it seems like a lot of busy work for not much payoff.
Not to mention the tedious changes to all the 'include' directives this will entail...
Since you get (or have gotten) lost browsing the code, this to me is another indication that I have to get serious about finishing a developers guide (easier said than done). BTW I browse the cpptraj code on my phone all the time and it's never bothered me, but I am a little biased :-)

**Comment by hainm** [comment]
>  I'm very resistant to this idea right now. The main problem I have when code is in different folders (an example that comes to mind is Gromacs) is that it then becomes more difficult for me to find out where specific functions are (since I don't have a fancy IDE). For example, if I want to find out where I've used integerToString() all I have to do now is grep -l "integerToString(" *.cpp. To me that's a cost that is not paid for by having things look a little nicer. In my opinion keeping the file names consistent (e.g. Action_X) is fine for the time being. Maybe as time goes on I'll warm up to this idea but right now it seems like a lot of busy work for not much payoff.

sure. I just label the issue as "low priority"

> Since you get (or have gotten) lost browsing the code, this to me is another indication that I have to get serious about finishing a developers guide (easier said than done).

yeah, this happened about a year ago with my very limited ability to read C++ code. But yeah, try to spend more time on doc and dev-guide. This is incredibly helpful for new developers to catch your idea. If possible, you can change 'lyx' format to markdown, rst or pdf so people can easily read it on web browser.

**Comment by swails** [comment]
+1 for moving to markdown (file extension `.md`).  Github has particularly good support for it (and you can use markdown for Github's Wiki as well).

So you can always put the devguide on the wiki attached to the repo, too.

**Comment by hainm** [comment]
+1 (= 2 from Hai and Jason). :))

**Comment by drroe** [comment]
So I've been converting the dev guide from Lyx to Markdown in a separate branch. I do like the overall formatting better, however I do have to say I miss the automatic table of contents generation. There doesn't seem to be an easy way to do this yet (although after a brief google search it seems other people seem to have the same concern). Not sure how much of a deal-breaker this is in the long run - it's clearly possible to just create some basic links at the beginning of the doc. I just hate doing things like that manually :-)

**Comment by hainm** [comment]
Have you try this python script yet?
https://github.com/rasbt/markdown-toclify

**Comment by drroe** [comment]
Seems interesting. I'll have to try it out.

**Comment by swails** [comment]
Oh yea!  I actually did something quite similar to generate the TOC for my Wiki.  If you clone my wiki page (see https://github.com/ParmEd/ParmEd.wiki.git), there's a script called generate_toc.py.  Just run it in your directory with all of your .md files and it will add TOC to it.

**Comment by swails** [comment]
You have to clone that repo:

```
git clone https://github.com/ParmEd/ParmEd.wiki.git
```

Then inside that repo.

**Comment by drroe** [comment]
Honestly I don't think I will ever do this unless a more compelling case can be made, so I'm going to close this.
