### ISSUE TITLE
should use HEATM for water?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#316]
hi,

I realize that cpptraj and parmed use different name in the first column of pdb file for water

parmed
-----------
```python
TER    6977      WAT  1702
HETATM 6978  O   WAT  1703      10.065   8.044  33.232  1.00  0.00           O
HETATM 6979  H1  WAT  1703      10.159   8.414  34.110  1.00  0.00           H
HETATM 6980  H2  WAT  1703      10.683   8.540  32.695  1.00  0.00           H
```

cpptraj
----------
```python
TER    5291      WAT  1703
ATOM   5291  O   WAT  1704       0.523   8.479  18.051  1.00  0.00           O
ATOM   5292  H1  WAT  1704       0.131   9.024  17.368  1.00  0.00           H
ATOM   5293  H2  WAT  1704      -0.178   8.360  18.693  1.00  0.00           H
```

Question
- Is this expected for cpptraj?

- if yes, does cpptraj intent to support to use 'HETATM'?

http://deposit.rcsb.org/adit/docs/pdb_atom_format.html#HETATM
```bash

Record:

HETATM

Contains:	the atomic coordinate records for atoms within "non-standard" 
groups. These records are used for water molecules and atoms presented in HET 
groups.
```

**Comment by swails** [comment]
The reason I started using `HETATM` instead of `ATOM` for non-standard residues is because Tinker is *incredibly* picky about that.  If you have ions labeled as `ATOM` instead of `HETATM`, Tinker fails.  If you call them `HETATM`s instead, it works.  But it doesn't fail with a helpful error message -- it just prints out a useless file.

So I didn't switch to dumping `HETATM` out of some purist tendencies -- it was entirely thanks to Tinker.

**Comment by drroe** [comment]
On its face it seems like the right thing to do. However, this will break backwards compatibility, so it's a cost-benefit thing. Also, if it were going to be implemented correctly it has to recognize all "non-standard" groups, not just water, which is a bit out of cpptraj's wheelhouse. My thought here is "if it ain't broke, don't fix it", i.e. unless there's a pressing need for cpptraj to do this I think its behavior should remain as-is.
