### ISSUE TITLE
add bleeding-edge compilers to travis build too?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#326]
https://github.com/Amber-MD/cpptraj/pull/325

**Comment by drroe** [comment]
I think this will be annoying to support. You would have to explicitly bring in the packages for the new compiler (e.g. `gfortran-6`), which are "bleeding edge" right now, but eventually will be standard and then obsolete, so you will have to constantly update what is "bleeding edge". Then there is the possibility that other packages (e.g. netcdf library, fftw3 etc) won't be compatible with the GLIBC that gets pulled in because of the newer compilers or something similar. In my opinion making sure that cpptraj works on what is considered "standard" is fine - if there are problems with newer compilers they can be raised as issues.
