### ISSUE TITLE
Improve SPAM functionality

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#42]
Current functionality can be improved. From @swails: "​The version included in AmberTools 14 and 15 _is_ more recent, but it is
still not well-automated -- it's work in progress.  The suggested method
for running SPAM calculations are to use the "volmap" command in cpptraj to
identify peaks in solvent density, then feed those peaks to the "spam"
command which can be used to reorganize water molecule indices (so the same
water appears in the same site every frame) and compute an energy-shifted
electrostatic and van der Waals interaction for that water.

It then dumps a time series of energies for each water site, which you need
to post-process (using numpy and scipy, for instance) into a free energy
(from which you can back-out the enthalpy and entropy).  The code in
SPAM.py provides code for turning this energy time-series into free
energies, although SPAM.py relies on a patched cpptraj from AmberTools12​.  You can use that as a template.  Hopefully SPAM.py can be updated to
work with the latest version of AmberTools and automate the part of the
procedure that cpptraj doesn't yet."

**Comment by swails** [comment]
On my to-do list :).  To do this in cpptraj, the main thing it needs is PME.  But it's going to require a lot of changing charges.  One of the big decisions we have here is how to do that:

1. Use the sander API?  Not terribly flexible as far as changing parameters on-the-fly, but it's Amber and has a *lot* of functionality (including QM/MM)
2. Pilfer a (C++) PME implementation from somewhere else?  I think Tim Giese wrote one for periodic RISM a little bit ago, and there's always the ones in Gromacs or OpenMM, which are license-compatible with cpptraj.

My personal vote is for 2, but we can probably get 1 to work.

**Comment by swails** [comment]
But since I wrote the original SPAM code, cpptraj has since gained other helpful stuff (particularly KDEs), so it's a lot more feasible to do this entirely within cpptraj than in times past.

**Comment by hainm** [comment]
@swails is it easy (for you) to update sander api so we can change the parameters on the fly?

**Comment by swails** [comment]
> @swails is it easy (for you) to update sander api so we can change the parameters on the fly?

Some parameters, yes.  Other parameters, doable but there are gotchas.  Other parameters are doable, but difficult, but most are well outside the range of what I would consider a reasonable task.

Examples:

Easy:
- Mass
- nonbonded index (so it can look like another L-J atom type *that already exists*)
- GB radii and screening factors
- changing any bonded parameter to another type *that already exists* (e.g., bonds, angles, or dihedrals)

Doable, with gotchas:
- Charge (some initialization depends on this, like the PME self-energy term, which needs to be re-done whenever charges are changed).

Not worth the effort:
- Adding any new parameters of any kind (e.g., zeroing-out bonds, angles, dihedrals, ...) that can't be done by simply redirecting a pointer to another existing type
- Adding a new L-J type
- Anything that would change the exclusion rules
- Changing any input parameters (e.g., cutoff, PME parameters, ... etc.)

The cleanest and most reliable way to change parameters is to call `sander_cleanup()` followed by `sander_setup()`, but that is *slow* if you need to do it a lot.  With SPAM, you'd need to do it 3 times *per frame per water binding site* -- changing L-J terms and charges.  If you don't process this as an action, and have all frames stored in memory to loop over them, you can reduce this to three times per water binding site, since each frame uses the same 3 parms for each water site.

I still might try to revive SPAM.py, since it has some nice little features (including a GUI) and I can hack efficient ways of using pysander or use OpenMM if available -- that's easier to do with Python than C++ (where you'd have to use `dlopen` and friends).

**Comment by drroe** [comment]
> Use the sander API?

I've actually done some preliminary work on getting cpptraj to use the sander API, enabled by '-sanderlib' configure flag (see stuff in Energy.{h,cpp} in USE_SANDERLIB defines). I did some testing but I don't remember how well it worked. 

> Pilfer a (C++) PME implementation from somewhere else?

What about using mdgx? Although I'm not opposed to any of the other options in my opinion it's simpler for now if we keep things within Amber/AmberTools.

**Comment by swails** [comment]
> What about using mdgx? Although I'm not opposed to any of the other options in my opinion it's simpler for now if we keep things within Amber/AmberTools.

It's not as isolated in the code.  To be clear, my plan was to take a PME implementation, in its entirety (it's not too much code), and dump it directly into cpptraj.  Which will be even more contained than using sander or something of that ilk.

**Comment by hainm** [comment]
> To be clear, my plan was to take a PME implementation, in its entirety (it's not too much code), and dump it directly into cpptraj.

I myself prefer to avoid duplicating code/implementation. Just naive question: with current `mdgx` code, it's really hard to isolate PME? (sorry for my C++ skill).

**Comment by drroe** [comment]
> To be clear, my plan was to take a PME implementation, in its entirety (it's not too much code), and dump it directly into cpptraj.

Then I can rename cpptraj...cppmetraj... (or maybe not)

**Comment by swails** [comment]
haha

**Comment by hainm** [comment]
ack. So I guess it's a joke.

**Comment by drroe** [comment]
@swails if no objections I will consider this addressed by #429. I feel that adding PME to SPAM (and CPPTRAJ in general) is really a separate issue.

**Comment by drroe** [comment]
Addressed by #429.
