### ISSUE TITLE
understand lifetime

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#527]
Dan,

Like we chat on gchat. Here what the code pytraj does

```
def lifetime(data, options='', dtype='dict'):
    """EXPERIMENTAL

    Parameters
    ----------
    data : 1D-array
    options : str
        cpptraj's options. Check cpptraj's manual (`pytraj.info("lifetime"))
    """
    cdslist = CpptrajDatasetList()

    # create datasetname so we can reference them
    name = 'input_data'
    if 'int' in data.dtype.name:
        cdslist.add("integer", name)
    else:
        cdslist.add("double", name)
    cdslist[-1].data = np.asarray(data)
    print('cdslist', cdslist.to_dict())

    act = c_analysis.Analysis_Lifetime()
    out_dname = 'name lifetime_out'
    cmd = ' '.join((name, options, out_dname))
    print('cmd', cmd)
    act(cmd, dslist=cdslist)

    for d in cdslist:
        print(d)

    # cdslist.remove_set(cdslist[name])
    return get_data_from_dtype(cdslist, dtype=dtype)
```

Here is the output of 
```
    for d in cdslist:
        print(d)
```

```
<pytraj.datasets.DatasetInteger: size=100, key=input_data> 
values: 
[1 0 0 ..., 0 0 1]
<pytraj.datasets.DatasetFloat: size=20, key=input_data> 
values: 
[ 0.40000001  0.60000002  0.         ...,  0.2         0.          0.40000001]
<pytraj.datasets.DatasetInteger: size=20, key=input_data> 
values: 
[1 3 0 ..., 1 0 1]
<pytraj.datasets.DatasetFloat: size=20, key=input_data> 
values: 
[ 1.  3.  0. ...,  1.  0.  1.]
<pytraj.datasets.DatasetDouble: size=4, key=curve:0> 
values: 
[ 1.          0.26315789  0.10526316  0.05263158]
```

It seems to me that cpptraj use the same "name" for some datasets here. Can you explain that? Also, how can I interpret the data?

**Comment by drroe** [comment]
I'm not completely clear on how pytraj is accessing the data from cpptraj, but I will provide some more details on what cpptraj is doing in the hopes that it clears things up for you.

The `lifetime` analysis command can generate a lot of data because it can be run for multiple data sets and over multiple time windows. If a window length is specified, 3 output sets are generated for each input data set (here "present" means input data satisfies lifetime criterion that frame):
- **`<name>:<idx>`** The average lifetime for each window, SUM[Present]/WindowSize.
- **`<name>[avg]:<idx>`** The average lifetime length for each window, SUM[Present]/Nlifetimes
- **`<name>[max]:<idx>`** The maximum lifetime length for each window, MAX[Present].

`<idx>` refers to the input data set.

If no window length is specified, the following data sets are generated:
- **`<name>`** Number of lifetimes for each set.
- **`<name>[avg]`** Average lifetime length for each set.
- **`<name>[max]`** Max lifetime for each set.
- **`<name>[frames]`** Total number of frames present for each set.
- **`<name>[frames]`** The name of each set.

Lifetime curve data sets are always generated for each input data set:
- **`<name>[curve]:<idx>`** The lifetime curve.

**Comment by hainm** [comment]
thanks Dan. Let me give it a try.

**Comment by hainm** [comment]
> If no window length is specified, the following data sets are generated:

why is it?
