### ISSUE TITLE
add "fast" target for Makefile?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#540]
Just for "make fast" in AmberTools. Ideally, "fast" should be < 10 s (ideally few seconds).

Current syntax is
```
cd some_folder && $(MAKE) fast
```

**Comment by drroe** [comment]
I'll work on this on Monday.

FYI, cpptraj does have a 'test.short' target which covers a lot of functionality and only takes only 16 s on my desktop. However, because dacdif is so heavyweight the AmberTools tests take 46 s...

**Comment by hainm** [comment]
On my mac, stand alone cpptraj "test.short" takes 43 s.

**Comment by drroe** [comment]
I'm having second thoughts about this. On my Macbook Pro (2.5 GHz i7) `make test.all` takes 53 s (not including the `Test_Esander` test). I don't think that is unreasonable considering all the various functionality that is tested. I can definitely work on shaving time off of the more expensive tests like `Test_Esander`, `Test_Volmap`, `Test_GIST`, `Test_Ewald`, and `Test_SPAM`, but I think that 10 s is an unreasonable constriction considering all of the functionality that is in cpptraj:
```
DEBUG: 186 commands.
DEBUG:	               General : 25
DEBUG:	                System : 1
DEBUG:	                Coords : 7
DEBUG:	            Trajectory : 5
DEBUG:	              Topology : 17
DEBUG:	                Action : 77
DEBUG:	              Analysis : 35
```

**Comment by drroe** [comment]
> On my mac, stand alone cpptraj "test.short" takes 43 s.

BTW this is because I forgot to update `make.short` to use the new test framework.

**Comment by hainm** [comment]
Hi

I am talking about 10 s (x >500 tests in AT) in the context of 'make fast'
target, not for the full test suite.

The (almost) full test suite still run nightly.

Hai

**Comment by drroe** [comment]
> I am talking about 10 s (x >500 tests in AT) in the context of 'make fast' target, not for the full test suite. 

I understand that. The purpose of making a `fast` target is to cut down on development time. Having to wait over an hour to run tests after every 'push' is unreasonable. However, the point of having a test suite at all is to ensure efficient development by reducing (ideally eliminating) bad commits, i.e. commits that break the build or introduce bugs. For a test suite to really work this way you have to cover lots (ideally all) of your code. If you cover less code then your tests will take less time, but now you've opened up your development to annoying bugs. Sure the nightly tests can then catch it, but that can be hours later and now the bug is now in the code history. In the meantime, people are free to pull that bug down to their local repositories. Again ultimately not fatal but it shouldn't happen in the first place.

Test for test, I would argue that the cpptraj test suite is currently the most efficient in AmberTools. On my Linux desktop the full cpptraj test suite of 132 tests takes 38 s, which is 0.29 s per test. Not including the 5 longest tests mentioned above it takes just under 20 s, which is 0.16 s per test. That's barely enough time to get up from your desk and stretch. Considering that cpptraj is one of the larger pieces of code in Amber, that's not bad. I think that if in total the AmberTools test suite takes about 5 minutes that is still a reasonable amount of time.

So rather than reduce test suite coverage, I propose doing the following for cpptraj tests first:
1. Reduce the amount of time taken by the larger tests; aiming for < 1 s per test.
2. Make the cpptraj test suite avoid `dacdif` inside AmberTools. It does a lot of preprocessing that is unnecessary for cpptraj output and adds a significant chunk of time to the tests. This should be easy to implement I think and just require that the cpptraj test framework write to TEST_FAILURES etc.

If the test suite time still seems unreasonable at that point I can try to consolidate/shrink some tests (without reducing coverage).

**Comment by hainm** [comment]
uhm, given that all test suite already covered in this repo , what could go wrong in AT?
(just want to make sure we are in the same page here).

**Comment by hainm** [comment]
oops, accidentally close.

**Comment by drroe** [comment]
> given that all test suite already covered in this repo , what could go wrong in AT?

CI testing is great, and thanks to Travis, Appveyor, and @swails lots of configurations of cpptraj are tested. But the current test framework doesn't cover every possible environment/compiler/etc (e.g. PGI compilers). In my view having a test target that is purposefully incomplete in terms of coverage is potentially dangerous and can give the impression that code is working when it really isn't. What I don't want to do is eliminate code coverage to meet some arbitrary test suite time limit.

IMO we should focus on making tests as fast a possible while still making sure the code gets a workout. The more I think about it, the more I'm convinced that omitting tests is really the wrong way to go about improving test suite speed. Why not reduce the size/length of needlessly expensive tests and eliminate redundant tests first and then see where we are?

**Comment by hainm** [comment]
> Why not reduce the size/length of needlessly expensive tests and eliminate redundant tests first and then see where we are?

yeah agree. I am buzzing people about this, starting with QMMM (some tests take 10 minutes :D).

**Comment by drroe** [comment]
Honestly I think the path to take here is to avoid using `dacdif`. Test timings for `test.all` on my machine:

With: 1m37.980s
Without: 0m26.721s

That's an _incredible_ amount of overhead. It shouldn't be hard to do but I need to make sure MasterTest.sh keeps the logging the same as dacdif when in AmberTools.

**Comment by hainm** [comment]
sounds good.

**Comment by drroe** [comment]
After PR #545 and #547 the CPPTRAJ tests in AmberTools now take ~47 s on my MacBook and ~25 s on my Linux desktop. I feel this is a reasonable amount of time for a fully-functional test suite, so I'll close this now. If there are still concerns feel free to re-open this issue or start a new one.
