### ISSUE TITLE
Add 'cphstats' functionality to cpptraj

### ISSUE THREAD

**Issue by drroe** [Amber-MD/cpptraj#55]
@swails Not a high priority, but I think this would be good to do at some point.

**Comment by swails** [comment]
Sounds good.  We should probably come up with some ideas for how this should optimally be done.

Should we create a new dataset subclass to handle protonation state data?  There should also be a way for these data sets to interact with trajectories (since you can assign frame-based protonation states from the cpout files) -- of course this could probably be done with `filter` just fine, too.

The analyses that you can do on constant pH data sets are all integer-based, but I'm not sure whether or not we should restrict those analyses to constant pH data sets or not (my feeling is yes, we should).

Or maybe you have an enumerated type that you use to label data types?  It's been awhile since I've looked at that part of cpptraj, and it's changed a lot since them.

**Comment by drroe** [comment]
Addressed by (#579 and #586). `cestats` can get it's own issue :-)
