### ISSUE TITLE
add "clear" command?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#557]
What do you think? similar to that in terminal.

**Comment by drroe** [comment]
This is surprisingly difficult to do "correctly", especially in a cross-platform way. It requires linking in yet another external library; the exact one depends on the platform (`ncurses` on Linux, `pdcurses` on Windows). You can cheat by using a `system()` call to `clear`/`cls` respectively, but over the past few years I've become aware that using `system()` is bad programming practice, which is why I haven't added any new system commands to cpptraj (I've actually been thinking about rewriting/removing the ones that are there). You can also cheat by just writing a ton of newlines to `stdout`, but that's not a great solution :-).

So I think the payoff here is not so great.

**Comment by hainm** [comment]
yeah, so close now.
