### ISSUE TITLE
volmap gridding according to center of mass

### ISSUE THREAD

**Issue by DDGmichigan** [Amber-MD/cpptraj#711]
Hi Daniel,
Similar to the grid command wherein you incorporated "byres" "bymol" keywords for COM binning, can a similar thing be implemented for volmap command as well?

Thanks

**Comment by drroe** [comment]
Good suggestion, I'll try to get to it soon.

**Comment by DDGmichigan** [comment]
[whole_200_C3N]$ $MPI_HOME/bin/mpiexec -n 4 cpptraj.MPI -i xplor_ptraj.in > cpptraj_all200.log
Error: [grid] Not all arguments handled: [ byres ]
        1 errors encountered reading input.
Error: Error(s) occurred during execution.

**Comment by drroe** [comment]
You need cpptraj version >= 4.11.7 (check via `cpptraj --internal-version` for older cpptraj) for `grid byres`.

**Comment by DDGmichigan** [comment]
cpptraj --version
CPPTRAJ: Version V4.14.5 (GitHub)


How do I compile cpptraj.MPI?

I tried
./configure -mpi gnu!

It says
  Testing C++ compiler:
Test compile failed: mpicxx  -Wall  -O3     -o testp testp.cpp
Error follows:
./configure: line 355: mpicxx: command not found

















Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by drroe** [comment]
> ./configure: line 355: mpicxx: command not found

As the message states, the configure script was unable to find the MPI C++ compiler wrapper mpicxx. You need to make sure that's in your PATH. Perhaps you need to load a module, or do something like `export PATH=$MPI_HOME/bin:$PATH`?

**Comment by DDGmichigan** [comment]
I fixed it. Thanks

**Comment by DDGmichigan** [comment]
Hi @drroe , can we get the center of mass grid through volmap command now? Its is  the byres keyword?
Thanks
Debarati

**Comment by drroe** [comment]
After thinking about this a bit more, I'm not sure that "by residue" or "by molecule" really makes sense for something like `volmap`. The `volmap` command works by spreading around a Gaussian density based on atomic radii. If you go to something like "by residue", what do you make that radius? I guess you could approximate a radius based on the size of the residue, but that's going to be a poor approximation for almost anything that's not spherical (which is really most things). For something like water it would work, but for water it's not necessary since it's so small. 

I'm going to ping @swails and invite him to comment here since he has extensive experience with `volmap`.

**Comment by DDGmichigan** [comment]
@drroe , when we use "byres" for generating xplor densities that makes sense, in cpptraj, as one may infer from COM xplor files versus all atom xplor file.. I am also not clear if the radius of the residue makes sense, my set of molecules I use as co-solvents are ethanol isopropanol acetonitrile and pyrimidine.. We cannot say all of these small probes are perfectly spherical! I am confused a bit!maybe Dr Swails can provide some insights on volmap. Not all is clear from the Amber18 manual

**Comment by swails** [comment]
I'm digging way back here (I think I added this originally around 2012).

As @drroe mentioned, volmap works by estimating "atom" densities by treating each atom as a 3-D Gaussian (which is spherically symmetrical).  It's unclear what you're trying to map when you say `byres` or `bymolecule` or something like that, or even what such a thing means.  Center of mass?  Center of geometry?  I don't really see much utility in these "fake" density maps.  Which isn't to say that there *is* no utility, but I think whatever applications exist are very specific.

I don't think the benefit of these very specific inquiries justifies the added code complexity and development time/effort involved in supporting every different flavor that people might want (COM, COG, COG of heavy-atoms-only, "backbone" COG, "backbone" COM, titratable group COM/COG, ...).

You can get things like water oxygen densities, backbone densities, alpha-carbon densities, etc. by just using the appropriate masks.  Since these densities correspond to actual atoms, it's easier to assign some kind of physical significance to them.

--------

IMO, this kind of investigation/measurement is precisely what [pytraj](https://github.com/Amber-MD/pytraj) was created to support.

You can read in any arbitrary Amber system or trajectory and write your own function to transform it into a "coarse-grained" representation that has atoms centered where you want them.

Want to use COG of specific residues to build a volmap?  Write a function that takes in a trajectory frame and writes out a new frame with an atom at the COG location.  You can do the same for COM (but the formula is different).  Or backbone COG, or titratable group COM, or...  Once you have that new trajectory (and you should be able to assign any radius you want to it), run it through cpptraj's `volmap` to get the quantity you want.

**Comment by hainm** [comment]
> Once you have that new trajectory (and you should be able to assign any radius you want to it), run it through cpptraj's volmap to get the quantity you want.

`pytraj` does that (via cpptraj, of course) too :p 
 
https://github.com/Amber-MD/pytraj/blob/1fea8ffd2163fd93f88dd5f3c0b4072aee51c63a/pytraj/all_actions.py#L870

**Comment by DDGmichigan** [comment]
I am not that much familiar with pytraj, so I have a trajectory and I want to get the densities of my acetonitrile (COM) peaks I need to write a function in pytraj to extract the COM peaks?
Maybe I got it wrong
@hainm  when you say pytraj does it? What all inputs I need for pytraj to run and get the COM location printed out?

**Comment by hainm** [comment]
hi @DDGmichigan: I am not familiar with your issue so I am not sure.

But the COM calculation is here: https://amber-md.github.io/pytraj/latest/_api/pytraj.all_actions.html#pytraj.all_actions.center_of_mass

> when you say pytraj does it? 

I mean user can call cpptraj'`s volmap via pytraj too.

**Comment by drroe** [comment]
No action on this for a few months, hopefully it is resolved.
