### ISSUE TITLE
rst command to create distance based restraints

### ISSUE THREAD

**Issue by DDGmichigan** [Amber-MD/cpptraj#852]
Hello,
So I found it on cpptraj manual but I am bit confused on what the output is. My goal is to create distance based restraints on my kinase:
Calpha Residue 87 to my probe C3N(C2atom)
Calpha Residue 89 to my probe C3N(C2atom)
Calpha Residue 137 to my probe C3N(C2atom)
 SO basically my objective is to  hold the probe central atom and the distance between these 3 C atoms of the binding site residues fixed.
 rst <mask1> <mask2> [<mask3>] [<mask4>] r1 <r1> r2 <r2> r3 <r3> r4 <r4> rk2 <rk2> rk3 <rk3> {[parm <parmfile / tag> | parmindex <#>]}[{ref <refname> | refindex <#> | reference} [offset <off>] [width <width>]] [out <outfile>]

My input file is 
parm complex_0_lamda_solvated.prmtop
reference complex_WAT_box_SITE1.pdb
rst ':274@C2' ':87@CA' reference offset 1 rk2 10.0 rk3 10.0 out output1
rst ':274@C2' ':89@CA' reference offset 1 rk2 10.0 rk3 10.0 out output2
rst ':274@C2' ':137@CA' reference offset 1 rk2 10.0 rk3 10.0 out output3
~
What is 10 in my input file I did not understand and I get output1, output2, output3 but I am not sure how to plug it in my mdin files.
Please help!
Thanks

**Comment by drroe** [comment]
Hi,

First, I highly recommend going over the "NMR Refinement" section of the Amber manual (section 27 in the Amber 20 manual), since this contains the full description of the syntax output by the `rst` command (which are NMR restraints). Second, I recommend redirecting the output of all three `rst` commands to a single file so that all the restraints end up in that file. You then need to reference that file in your MDIN after the `&ctrl` namelist, e.g.:

cpptraj:
```
rst ':274@C2' ':87@CA' reference offset 1 rk2 10.0 rk3 10.0 out output.disang
rst ':274@C2' ':89@CA' reference offset 1 rk2 10.0 rk3 10.0 out output.disang
rst ':274@C2' ':137@CA' reference offset 1 rk2 10.0 rk3 10.0 out output.disang
```

MD input:
```
sample MDIN
&cntrl
  <namelist variables>,
   nmropt=1,
&end
&wt
   TYPE="END",
&end
DISANG=output.disang
 ```

The `nmropt=1` turns on the NMR restraints, DISANG points to the file where the restraints are defined. Again I really recommend reading the relevant sections of the manual. Also run a short (nstlim=10 or something) test run and check the output file to make sure all looks well before you do a production run - NMR restraints can be a bit tricky to deal with. Hope this helps.

**Comment by DDGmichigan** [comment]
Hello Dan,
I have two questions regarding the distance restraints:
Should I be using only residues ( CA atoms) in the binding site to tether my acetonitrile in place? Should it matter what residues I choose as as long as I have 3 spread out CA atoms to tether distances to my central C2 atom of my acetonitrile?
Also in my initial.pdb file say  I found that these conditions are true:
distance  calculated from CA atom TRP 220 to C2 atom C3N is 3.8 Angstroms
distance  calculated from CA atom GLU 216 to C2 atom C3N is 7.3  Angstroms
distance  calculated from CA atom LEU 241  to C2 atom C3N is 11 Angstroms

How should I incorporate this information in my disang file?
![3_distance_restraints](https://user-images.githubusercontent.com/48214273/96759724-6ed6c580-13a6-11eb-92b1-404a7a8338a5.JPG)

**Comment by DDGmichigan** [comment]
Input file used 
parm complex_0_lamda_solvated.prmtop
reference complex_WAT_box_SITE2.pdb
rst ':274@C2' ':220@CA' reference offset 0.5 rk2 10.0 rk3 10.0 out output.disang
rst ':274@C2' ':225@CA' reference offset 0.5 rk2 10.0 rk3 10.0 out output.disang
rst ':274@C2' ':216@CA' reference offset 0.5  rk2 10.0 rk3 10.0 out output.disang
go

Output I got is output.disang
 &rst iat=4393,3467,0
   r1=3.823274, r2=4.323274, r3=4.323274, r4=4.823274, rk2=10.000000, rk3=10.000000,
   nstep1=0, nstep2=0,
 &end
 &rst iat=4393,3572,0
   r1=3.614876, r2=4.114876, r3=4.114876, r4=4.614876, rk2=10.000000, rk3=10.000000,
   nstep1=0, nstep2=0,
 &end
 &rst iat=4393,3408,0
   r1=7.302151, r2=7.802151, r3=7.802151, r4=8.302151, rk2=10.000000, rk3=10.000000,
   nstep1=0, nstep2=0,
 &end

I am not sure why is iat=4393 and what are the numbers 3467 3572 comma separated from iat=4593?

**Comment by drroe** [comment]
> We should have a single force constant to keep the distance restraints in place why is there 2 force constants?

This is why I suggested you read the 'NMR refinement' section of the Amber manual since these variables are explained there. I should have mentioned that Cpptraj uses the same restraint variable names as sander:

**r1->r4, rk2, rk3, r1a->r4a, rk2a, rk3a** : If IALTD=0, the restraint is a well with a square bottom with parabolic sides out to a defined distance, and then linear sides beyond that. If R is the value of the restraint in question:
• R < r1 Linear, with the slope of the "left-hand" parabola at the point R=r1.
• r1 <= R < r2 Parabolic, with restraint energy k2(R-r2)^2.
• r2 <= R < r3 E = 0.
• r3 <= R < r4 Parabolic, with restraint energy k3(R-r3)^2.
• r4 <= R Linear, with the slope of the "right-hand" parabola at the point R=r4.

So there are two force constants because there are two parts of the restraint that use them: r1 <= R < r2 and r3 <= R < r4. This gives you maximum flexibility in setting up your restraint. Does that clear things up?

**Comment by DDGmichigan** [comment]
I guess a little bit, I had read that nmr restraint section twice, it was not very clear due to lack of examples...Sorry.
But I was wondering what is the best way to cross check whether my restraints are being correctly read from  the output.disang file I created?
should I print out distance of these atoms to my C3N(C2) each frame and then cross check how it moves or is there something else you would recommend?
Thank you Dan!

**Comment by drroe** [comment]
> But I was wondering what is the best way to cross check whether my restraints are being correctly read from the output.disang file I created?

There will be something in the MDOUT file about a number of restraints read. You can also set the `DUMPAVE` file (same section as `DISANG`) with DUMPFREQ variable set to 1 to get the values printed at each step (again see the manual). Only do this for a test of like 100 steps or so because you'll generate a ton of data otherwise.

**Comment by DDGmichigan** [comment]
Thanks Dan!
This helps so much.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by drroe** [comment]
Seems this is resolved - please reopen if not.
