### ISSUE TITLE
how to tag ensemble run for Dispatch?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#86]
So I have two situations with identical input but giving different result

input

```python
parm ala2.99sb.mbondi2.parm7
trajin rem.nc.000 remdtraj remdtrajtemp 300.
rms out test.dat
```

If using `Command::ProcessInput(CpptrajState&, std::string const&)` to load to CpptrajState, I got what I am expecting (rmsd calculation for only 300-K frames).

however, I am using 'Command:Dispatch` to dispatch each line of above input (with CpptrajState), I got rmsd for rem.nc.000 instead.

Looking at cpptraj's code, `TrajinList` need to be tagged with 'ENSEMBLE' to get correct result. 

So my question is

* how to tag it with current CpptrajState

* is it possible to make `RunEnsemble` so we don't need to tag at all.

* what's your best solution?

**Comment by drroe** [comment]
> Looking at cpptraj's code, TrajinList need to be tagged with 'ENSEMBLE' to get correct result.

No, `ensemble` is only active when `ensemble` commands have been issued. In cpptraj `trajin` means you will be processing one frame at a time and `ensemble` means you will be processing multiple frames at a time. They have their own functions in CpptrajState, RunNormal() and RunEnsemble() respectively.

Since ProcessInput() calls Dispatch() (Command.cpp, line 295) and in fact the former is just a wrapper around the latter that gets and formats input from a file/STDIN, I really can't say what might be going wrong without seeing an example of your code.

**Comment by hainm** [comment]
> I really can't say what might be going wrong without seeing an example of your code.

I will look further.

**Comment by hainm** [comment]
just check and this is due to text string stuff in Python. close now.
